version: "3.9"

services:
  task-shop-react:
    container_name: task-shop-react
    build:
      context: .
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3030:3000
    volumes:
      - ./application:/application
    networks:
      - task-shop-react

networks:
  task-shop-react:
    name: task-shop-react
    driver: bridge
